### ISSUE TITLE
Estudar HTTP 

### ISSUE THREAD

**Issue by juliasilveira** [mirabolante/jogo-web#30]

**Comment by juliasilveira** [comment]
Vídeos do Tim Berners-Lee:

- [The Next Web](https://www.ted.com/talks/tim_berners_lee_the_next_web/transcript#t-197596)
- [The year open data went worldwide](https://www.ted.com/talks/tim_berners_lee_the_year_open_data_went_worldwide)
- [A Magna carta for the web](https://www.ted.com/talks/tim_berners_lee_a_magna_carta_for_the_web)

Vídeo do Code.org:

- [The Internet: HTTP & HTML](https://www.youtube.com/watch?v=kBXQZMmiA4s)

Vídeo do NICbrvideos:

- [HTTP2](https://www.youtube.com/watch?v=GrHtpPksUF4)

**Comment by juliasilveira** [comment]
Estudo concluído.

**Comment by SabrinaVillela** [comment]
Estudo concluído.
