### ISSUE TITLE
Estudar HTTPS

### ISSUE THREAD

**Issue by juliasilveira** [mirabolante/jogo-web#33]

**Comment by juliasilveira** [comment]
Ler os seguintes capítulos do livro High Performance Browser Networking:
- [TLS](https://hpbn.co/transport-layer-security-tls/);
- [WebSocket](https://hpbn.co/websocket/);
- [WebRTC](https://hpbn.co/webrtc/).

**Comment by juliasilveira** [comment]
Estudo concluído.

**Comment by SabrinaVillela** [comment]
Estudo concluído.
