### ISSUE TITLE
Usar imagem genérica de fundo

### ISSUE THREAD

**Issue by juliasilveira** [mirabolante/jogo-web#6]

**Comment by SabrinaVillela** [comment]
Momentaneamente vamos utilizar o seguinte background: https://opengameart.org/content/bevouliin-free-space-background

**Comment by SabrinaVillela** [comment]
Momentaneamente usaremos o seguinte background: https://opengameart.org/content/bevouliin-free-space-background

**Comment by SabrinaVillela** [comment]
Momentaneamente usaremos o seguinte plano de fundo: https://opengameart.org/content/bevouliin-free-space-background

**Comment by juliasilveira** [comment]
Por enquanto, será adotada a [Lemcraft](https://opengameart.org/content/lemcraft) e a [Dirt Platformer Tiles](https://opengameart.org/content/dirt-platformer-tiles) para desenhar um tiled map com chão, plataformas e céu.
