### ISSUE TITLE
Usar sprites genéricos de animação

### ISSUE THREAD

**Issue by juliasilveira** [mirabolante/jogo-web#7]

**Comment by SabrinaVillela** [comment]
Momentaneamente serão utilizados os seguintes sprites:
Sprite de personagem: https://opengameart.org/content/astronaut-0
Sprite de plataforma: https://opengameart.org/content/platforms
Sprite de ícones: https://opengameart.org/content/space-pixel-art

**Comment by juliasilveira** [comment]
Por enquanto, serão usados os sprites de personagem [Astronaut](https://opengameart.org/content/astronaut-0) e os ícones [Spike Monsters](https://opengameart.org/content/bevouliin-free-ingame-items-spike-monsters) e [Gems](https://opengameart.org/content/cc0-gem-icons).
